import json
import tempfile
import unittest
from pathlib import Path

from edi.product_api import build_snapshot, write_snapshot


class ProductApiTests(unittest.TestCase):
    def test_build_snapshot_contains_stable_sections(self) -> None:
        snapshot = build_snapshot(Path("."), "2026-05-23T00:00:00+00:00")

        self.assertEqual(snapshot["api_version"], "v1")
        self.assertIn("product", snapshot)
        self.assertIn("executive", snapshot)
        self.assertIn("risk", snapshot)
        self.assertIn("ai_agents", snapshot)
        self.assertIn("scanner_tuning", snapshot)
        self.assertIn("operationalization", snapshot)
        self.assertIn("v2", snapshot)
        self.assertIn("v3", snapshot)
        self.assertIn("v4", snapshot)
        self.assertIn("v5", snapshot)
        self.assertIn("substrate", snapshot)
        self.assertIn("dip", snapshot)
        self.assertGreater(snapshot["product"]["completion_percent"], 0)
        self.assertIsInstance(snapshot["executive"]["top_decisions"], list)
        self.assertGreater(snapshot["risk"]["runtime_signal_count"], 0)
        self.assertGreaterEqual(snapshot["ai_agents"]["capability_count"], 0)
        self.assertGreaterEqual(snapshot["scanner_tuning"]["candidate_count"], 0)
        self.assertGreaterEqual(snapshot["operationalization"]["review_workflow_count"], 0)
        self.assertEqual(snapshot["v2"]["acceptance_state"], "pass")
        self.assertEqual(snapshot["v3"]["acceptance_state"], "pass")
        self.assertGreaterEqual(snapshot["v3"]["connector_count"], 6)
        self.assertEqual(snapshot["v4"]["acceptance_state"], "pass")
        self.assertGreaterEqual(snapshot["v4"]["connector_count"], 6)
        self.assertEqual(snapshot["v5"]["tooling_completion_percent"], 100.0)
        self.assertGreaterEqual(snapshot["v5"]["live_claim_completion_percent"], 0.0)
        self.assertLess(snapshot["v5"]["live_claim_completion_percent"], 100.0)
        self.assertIn("autonomous production enforcement is active", snapshot["v5"]["blocked_claims"])
        self.assertIn("complete live runtime truth exists", snapshot["v5"]["blocked_claims"])
        self.assertEqual(snapshot["substrate"]["policy_completion_percent"], 100.0)
        self.assertGreater(snapshot["substrate"]["live_evidence_completion_percent"], 0.0)
        self.assertLess(snapshot["substrate"]["live_evidence_completion_percent"], 100.0)
        self.assertEqual(snapshot["substrate"]["promotion_order"], ["dev", "test", "staging", "prod"])
        self.assertEqual(snapshot["dip"]["policy_readiness_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_1_pre_runtime_trust_loop_skeleton_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_2_backlog_defined_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_2_backlog_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_3_computed_policy_diff_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_3_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_4_computed_simulation_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_4_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_5_durable_case_approval_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_5_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_6_identity_rbac_approval_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_6_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_7_repository_governance_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_7_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_8_release_lifecycle_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_8_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_9_external_identity_contract_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_9_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_0_durable_store_contract_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_0_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_1_governance_enforcement_parity_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_1_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_2_product_review_surface_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_2_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_3_multi_domain_simulation_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_3_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_4_capability_governance_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_4_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_5_shared_context_contract_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_5_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v2_0_runtime_readiness_assessment_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_0_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v2_1_governed_exception_schema_stability_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_1_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["independent_human_review_observed"])
        self.assertEqual(snapshot["dip"]["v2_2_external_approval_boundary_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_2_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["live_external_approval_system_observed"])
        self.assertEqual(snapshot["dip"]["v2_3_durable_case_store_adapter_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_3_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["production_durable_case_store_backend_observed"])
        self.assertEqual(snapshot["dip"]["v2_4_evidence_store_adapter_parity_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_4_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["adapter_runtime_backend_invoked"])
        self.assertEqual(snapshot["dip"]["v2_5_policy_engine_hardening_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_5_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["policy_engine_runtime_authority_observed"])
        self.assertEqual(snapshot["dip"]["pre_runtime_completion_scope_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["pre_runtime_completion_scope_label"], "complete_runtime_blocked")
        self.assertEqual(snapshot["dip"]["maturity_status_labels"]["policy_preflight"], "computed_for_first_fixture")
        self.assertEqual(
            snapshot["dip"]["maturity_status_labels"]["policy_engine"],
            "deterministic_policy_engine_lifecycle_and_precedence_validated",
        )
        self.assertEqual(snapshot["dip"]["deterministic_policy_engine_readiness_percent"], 80.0)
        self.assertEqual(snapshot["dip"]["computed_simulation_diff_readiness_percent"], 80.0)
        self.assertEqual(snapshot["dip"]["durable_case_store_readiness_percent"], 90.0)
        self.assertEqual(snapshot["dip"]["identity_backed_approval_readiness_percent"], 65.0)
        self.assertEqual(snapshot["dip"]["release_management_readiness_percent"], 85.0)
        self.assertEqual(snapshot["dip"]["runtime_execution_readiness_percent"], 0.0)
        self.assertEqual(snapshot["dip"]["production_decision_authority_percent"], 0.0)
        self.assertEqual(snapshot["dip"]["implementation_backlog_defined_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["implementation_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["target_repo_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["target_repo_governance_clean_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["approver_subject"], "Raghurammutya@gmail.com")
        self.assertEqual(snapshot["dip"]["target_repo_state"], "local_pre_runtime_trust_loop_observed")
        self.assertEqual(snapshot["dip"]["first_wedge"], "Governed Decision Review and Simulation")

    def test_write_snapshot_materializes_json(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "api.json"

            snapshot = write_snapshot(Path("."), out, "2026-05-23T00:00:00+00:00")

            written = json.loads(out.read_text(encoding="utf-8"))
            self.assertEqual(written["api_version"], "v1")
            self.assertEqual(written["generated_at"], snapshot["generated_at"])


if __name__ == "__main__":
    unittest.main()
