import json
import tempfile
import unittest
from pathlib import Path

from edi.product_api import build_snapshot, write_snapshot


class ProductApiTests(unittest.TestCase):
    def test_build_snapshot_contains_stable_sections(self) -> None:
        snapshot = build_snapshot(Path("."), "2026-05-23T00:00:00+00:00")

        self.assertEqual(snapshot["api_version"], "v1")
        self.assertIn("product", snapshot)
        self.assertIn("executive", snapshot)
        self.assertIn("risk", snapshot)
        self.assertIn("ai_agents", snapshot)
        self.assertIn("scanner_tuning", snapshot)
        self.assertIn("operationalization", snapshot)
        self.assertIn("v2", snapshot)
        self.assertIn("v3", snapshot)
        self.assertIn("v4", snapshot)
        self.assertIn("v5", snapshot)
        self.assertIn("substrate", snapshot)
        self.assertIn("dip", snapshot)
        self.assertGreater(snapshot["product"]["completion_percent"], 0)
        self.assertIsInstance(snapshot["executive"]["top_decisions"], list)
        self.assertGreater(snapshot["risk"]["runtime_signal_count"], 0)
        self.assertGreaterEqual(snapshot["ai_agents"]["capability_count"], 0)
        self.assertGreaterEqual(snapshot["scanner_tuning"]["candidate_count"], 0)
        self.assertGreaterEqual(snapshot["operationalization"]["review_workflow_count"], 0)
        self.assertEqual(snapshot["v2"]["acceptance_state"], "pass")
        self.assertEqual(snapshot["v3"]["acceptance_state"], "pass")
        self.assertGreaterEqual(snapshot["v3"]["connector_count"], 6)
        self.assertEqual(snapshot["v4"]["acceptance_state"], "pass")
        self.assertGreaterEqual(snapshot["v4"]["connector_count"], 6)
        self.assertEqual(snapshot["v5"]["tooling_completion_percent"], 100.0)
        self.assertGreaterEqual(snapshot["v5"]["live_claim_completion_percent"], 0.0)
        self.assertLess(snapshot["v5"]["live_claim_completion_percent"], 100.0)
        self.assertIn("autonomous production enforcement is active", snapshot["v5"]["blocked_claims"])
        self.assertIn("complete live runtime truth exists", snapshot["v5"]["blocked_claims"])
        self.assertEqual(snapshot["substrate"]["policy_completion_percent"], 100.0)
        self.assertGreater(snapshot["substrate"]["live_evidence_completion_percent"], 0.0)
        self.assertLess(snapshot["substrate"]["live_evidence_completion_percent"], 100.0)
        self.assertEqual(snapshot["substrate"]["promotion_order"], ["dev", "test", "staging", "prod"])
        self.assertEqual(snapshot["dip"]["policy_readiness_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_1_pre_runtime_trust_loop_skeleton_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_2_backlog_defined_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_2_backlog_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_3_computed_policy_diff_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_3_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_4_computed_simulation_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_4_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_5_durable_case_approval_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_5_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_6_identity_rbac_approval_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_6_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_7_repository_governance_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_7_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_8_release_lifecycle_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_8_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v0_9_external_identity_contract_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v0_9_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_0_durable_store_contract_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_0_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_1_governance_enforcement_parity_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_1_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_2_product_review_surface_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_2_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_3_multi_domain_simulation_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_3_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_4_capability_governance_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_4_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v1_5_shared_context_contract_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v1_5_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v2_0_runtime_readiness_assessment_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_0_status_label"], "completed_pre_runtime")
        self.assertEqual(snapshot["dip"]["v2_1_governed_exception_schema_stability_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_1_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["independent_human_review_observed"])
        self.assertEqual(snapshot["dip"]["v2_2_external_approval_boundary_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_2_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["live_external_approval_system_observed"])
        self.assertEqual(snapshot["dip"]["v2_3_durable_case_store_adapter_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_3_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["production_durable_case_store_backend_observed"])
        self.assertEqual(snapshot["dip"]["v2_4_evidence_store_adapter_parity_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_4_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["adapter_runtime_backend_invoked"])
        self.assertEqual(snapshot["dip"]["v2_5_policy_engine_hardening_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_5_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["policy_engine_runtime_authority_observed"])
        self.assertEqual(snapshot["dip"]["v2_6_external_approval_adapter_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_6_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["external_approval_adapter_live_system_observed"])
        self.assertFalse(snapshot["dip"]["external_approval_adapter_ai_approval_allowed"])
        self.assertEqual(snapshot["dip"]["v2_7_live_identity_rbac_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_7_status_label"], "completed_pre_runtime_mfa_claim_blocked")
        self.assertEqual(snapshot["dip"]["live_identity_rbac_provider"], "github")
        self.assertFalse(snapshot["dip"]["live_identity_rbac_mfa_claim_observed"])
        self.assertEqual(snapshot["dip"]["v2_8_durable_evidence_backend_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_8_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["durable_evidence_backend_runtime_invoked"])
        self.assertEqual(snapshot["dip"]["v2_9_release_promotion_rollback_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v2_9_status_label"], "completed_pre_runtime")
        self.assertFalse(snapshot["dip"]["prod_deployment_executed"])
        self.assertEqual(snapshot["dip"]["v3_0_pre_runtime_ga_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v3_0_status_label"], "complete_runtime_blocked")
        self.assertEqual(snapshot["dip"]["v3_1_governance_closure_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v3_1_status_label"], "completed_pre_runtime_exception_preserved")
        self.assertEqual(snapshot["dip"]["v3_2_external_identity_integration_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v3_2_external_identity_live_ready"])
        self.assertEqual(snapshot["dip"]["v3_3_external_approval_system_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v3_3_external_approval_system_live_ready"])
        self.assertEqual(snapshot["dip"]["v3_4_production_case_store_boundary_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v3_4_production_case_store_live_ready"])
        self.assertEqual(snapshot["dip"]["v3_5_runtime_control_plane_design_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v3_6_advisory_runtime_pilot_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v4_0_limited_runtime_authority_gate_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v4_0_limited_runtime_authority_granted"])
        self.assertEqual(snapshot["dip"]["v4_1_live_identity_evidence_gate_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v4_1_live_identity_authority_ready"])
        self.assertEqual(snapshot["dip"]["v4_2_live_approval_provider_gate_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v4_2_live_approval_provider_ready"])
        self.assertEqual(snapshot["dip"]["v4_3_production_case_store_gate_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v4_3_production_case_store_live_ready"])
        self.assertEqual(snapshot["dip"]["v4_4_release_promotion_execution_gate_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v4_4_prod_deployment_executed"])
        self.assertEqual(snapshot["dip"]["v5_0_governed_advisory_runtime_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v5_0_side_effects_executed"])
        self.assertEqual(snapshot["dip"]["v5_5_controlled_runtime_execution_gate_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v5_5_controlled_runtime_execution_authorized"])
        self.assertEqual(snapshot["dip"]["v6_0_platform_hardening_assessment_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v6_0_platform_production_ready"])
        self.assertEqual(snapshot["dip"]["v6_1_live_identity_authority_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v6_1_live_identity_authority_ready"])
        self.assertFalse(snapshot["dip"]["v6_1_mfa_claim_observed"])
        self.assertEqual(snapshot["dip"]["v6_2_live_decision_approval_provider_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v6_2_live_decision_approval_provider_ready"])
        self.assertFalse(snapshot["dip"]["v6_2_ai_approval_allowed"])
        self.assertEqual(snapshot["dip"]["v6_3_production_durable_case_store_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v6_3_production_durable_case_store_ready"])
        self.assertEqual(snapshot["dip"]["v6_4_production_promotion_chain_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v6_4_production_promotion_ready"])
        self.assertEqual(snapshot["dip"]["v7_0_controlled_runtime_pilot_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v7_0_controlled_runtime_pilot_authorized"])
        self.assertEqual(snapshot["dip"]["v7_5_marketplace_runtime_governance_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v7_5_marketplace_runtime_invocation_authorized"])
        self.assertFalse(snapshot["dip"]["v7_5_unrestricted_marketplace_execution_allowed"])
        self.assertEqual(snapshot["dip"]["v8_0_shared_context_runtime_governance_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v8_0_runtime_context_exchange_authorized"])
        self.assertFalse(snapshot["dip"]["v8_0_direct_database_access_allowed"])
        self.assertEqual(snapshot["dip"]["v9_0_production_authority_readiness_review_percent"], 100.0)
        self.assertFalse(snapshot["dip"]["v9_0_production_decision_authority_granted"])
        self.assertEqual(snapshot["dip"]["v10_0_completion_plan_execution_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v10_0_reviewed_step_count"], 9)
        self.assertEqual(snapshot["dip"]["v10_0_evidence_gate_complete_count"], 9)
        self.assertEqual(snapshot["dip"]["v10_0_live_completion_achieved_count"], 0)
        self.assertGreaterEqual(snapshot["dip"]["v10_0_blocked_live_completion_count"], 9)
        self.assertTrue(snapshot["dip"]["v10_0_product_vision_alignment_valid"])
        self.assertTrue(snapshot["dip"]["v10_0_ai_policy_boundary_preserved"])
        self.assertTrue(snapshot["dip"]["v10_0_runtime_authority_grant_blocked"])
        self.assertTrue(snapshot["dip"]["v10_0_production_decision_authority_blocked"])
        self.assertEqual(snapshot["dip"]["v11_0_api_first_platform_foundation_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v11_0_status_label"], "contract_complete_runtime_blocked")
        self.assertTrue(snapshot["dip"]["v11_0_rest_authoritative"])
        self.assertTrue(snapshot["dip"]["v11_0_websocket_notification_only"])
        self.assertFalse(snapshot["dip"]["v11_0_forced_microservice_topology"])
        self.assertFalse(snapshot["dip"]["v11_0_edi_universal_governance_store"])
        self.assertFalse(snapshot["dip"]["v11_0_direct_database_access_allowed"])
        self.assertTrue(snapshot["dip"]["v11_0_runtime_authority_blocked"])
        self.assertEqual(snapshot["dip"]["v15_0_api_foundation_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v15_0_status_label"], "contract_complete_runtime_blocked")
        self.assertEqual(snapshot["dip"]["v12_0_certified_capability_count"], 0)
        self.assertEqual(snapshot["dip"]["v12_0_runtime_invocation_allowed_count"], 0)
        self.assertFalse(snapshot["dip"]["v13_0_cross_product_database_access_allowed"])
        self.assertEqual(snapshot["dip"]["v13_0_runtime_authority_granted_count"], 0)
        self.assertTrue(snapshot["dip"]["v14_0_rest_authoritative"])
        self.assertTrue(snapshot["dip"]["v14_0_runtime_authority_default_blocked"])
        self.assertTrue(snapshot["dip"]["v15_0_event_recovery_contract_valid"])
        self.assertFalse(snapshot["dip"]["v15_0_websocket_authoritative"])
        self.assertFalse(snapshot["dip"]["v15_0_events_mutate_business_state"])
        self.assertTrue(snapshot["dip"]["v15_0_rest_recovery_required"])
        self.assertTrue(snapshot["dip"]["v15_0_api_foundation_valid"])
        self.assertEqual(snapshot["dip"]["v20_0_architecture_closure_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v20_0_status_label"], "architecture_closed_runtime_blocked")
        self.assertTrue(snapshot["dip"]["v16_0_certification_evidence_packs_valid"])
        self.assertEqual(snapshot["dip"]["v16_0_certified_service_count"], 0)
        self.assertEqual(snapshot["dip"]["v16_0_runtime_invocation_allowed_count"], 0)
        self.assertTrue(snapshot["dip"]["v17_0_product_pack_admission_valid"])
        self.assertFalse(snapshot["dip"]["v17_0_direct_database_access_allowed"])
        self.assertFalse(snapshot["dip"]["v17_0_hidden_shared_state_allowed"])
        self.assertEqual(snapshot["dip"]["v17_0_runtime_authority_granted_count"], 0)
        self.assertTrue(snapshot["dip"]["v18_0_openapi_skeleton_valid"])
        self.assertTrue(snapshot["dip"]["v18_0_runtime_authority_blocked_response"])
        self.assertTrue(snapshot["dip"]["v19_0_event_recovery_fixtures_valid"])
        self.assertFalse(snapshot["dip"]["v19_0_websocket_authoritative"])
        self.assertFalse(snapshot["dip"]["v19_0_events_mutate_business_state"])
        self.assertTrue(snapshot["dip"]["v19_0_all_events_recoverable"])
        self.assertTrue(snapshot["dip"]["v20_0_governance_store_logical_schema_valid"])
        self.assertFalse(snapshot["dip"]["v20_0_storage_backend_selected"])
        self.assertFalse(snapshot["dip"]["v20_0_direct_database_access_allowed"])
        self.assertTrue(snapshot["dip"]["v20_0_append_only_required"])
        self.assertTrue(snapshot["dip"]["v20_0_architecture_closure_valid"])
        self.assertEqual(snapshot["dip"]["v25_0_contract_closure_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v25_0_status_label"], "contract_closed_runtime_blocked")
        self.assertTrue(snapshot["dip"]["v21_0_canonical_openapi_contract_valid"])
        self.assertTrue(snapshot["dip"]["v21_0_rest_authoritative"])
        self.assertTrue(snapshot["dip"]["v21_0_all_commands_require_idempotency"])
        self.assertTrue(snapshot["dip"]["v21_0_all_commands_require_correlation"])
        self.assertTrue(snapshot["dip"]["v21_0_runtime_authority_blocked_response"])
        self.assertFalse(snapshot["dip"]["v21_0_websocket_authoritative"])
        self.assertTrue(snapshot["dip"]["v22_0_product_pack_contract_kit_valid"])
        self.assertFalse(snapshot["dip"]["v22_0_direct_database_access_allowed"])
        self.assertFalse(snapshot["dip"]["v22_0_hidden_shared_state_allowed"])
        self.assertEqual(snapshot["dip"]["v22_0_runtime_authority_granted_count"], 0)
        self.assertTrue(snapshot["dip"]["v23_0_adapter_evidence_contract_kit_valid"])
        self.assertEqual(snapshot["dip"]["v23_0_live_invocation_allowed_count"], 0)
        self.assertTrue(snapshot["dip"]["v24_0_governance_store_logical_api_valid"])
        self.assertFalse(snapshot["dip"]["v24_0_storage_backend_selected"])
        self.assertFalse(snapshot["dip"]["v24_0_direct_database_access_allowed"])
        self.assertFalse(snapshot["dip"]["v24_0_delete_operation_allowed"])
        self.assertTrue(snapshot["dip"]["v25_0_event_recovery_contract_v2_valid"])
        self.assertFalse(snapshot["dip"]["v25_0_websocket_authoritative"])
        self.assertFalse(snapshot["dip"]["v25_0_events_mutate_business_state"])
        self.assertTrue(snapshot["dip"]["v25_0_contract_closure_valid"])
        self.assertEqual(snapshot["dip"]["v30_0_platform_operating_model_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["v30_0_status_label"], "platform_operating_model_closed_runtime_blocked")
        self.assertTrue(snapshot["dip"]["v26_0_certification_workflow_valid"])
        self.assertEqual(snapshot["dip"]["v26_0_certified_count"], 0)
        self.assertEqual(snapshot["dip"]["v26_0_runtime_invocation_allowed_count"], 0)
        self.assertTrue(snapshot["dip"]["v27_0_runtime_authority_gate_contract_valid"])
        self.assertFalse(snapshot["dip"]["v27_0_runtime_authority_granted"])
        self.assertTrue(snapshot["dip"]["v27_0_negative_fixtures_block_authority"])
        self.assertTrue(snapshot["dip"]["v28_0_cost_usage_evidence_contract_valid"])
        self.assertFalse(snapshot["dip"]["v28_0_billing_integration_enabled"])
        self.assertEqual(snapshot["dip"]["v28_0_live_invocation_observed_count"], 0)
        self.assertTrue(snapshot["dip"]["v29_0_semantic_projection_contract_valid"])
        self.assertFalse(snapshot["dip"]["v29_0_direct_database_access_allowed"])
        self.assertFalse(snapshot["dip"]["v29_0_runtime_context_exchange_authorized"])
        self.assertTrue(snapshot["dip"]["v30_0_product_pack_developer_kit_valid"])
        self.assertEqual(snapshot["dip"]["v30_0_runtime_authority_granted_count"], 0)
        self.assertFalse(snapshot["dip"]["v30_0_direct_database_access_allowed"])
        self.assertTrue(snapshot["dip"]["v30_0_platform_operating_model_closure_valid"])
        self.assertEqual(snapshot["dip"]["pre_runtime_completion_scope_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["pre_runtime_completion_scope_label"], "complete_runtime_blocked")
        self.assertEqual(snapshot["dip"]["maturity_status_labels"]["policy_preflight"], "computed_for_first_fixture")
        self.assertEqual(
            snapshot["dip"]["maturity_status_labels"]["policy_engine"],
            "deterministic_policy_engine_lifecycle_and_precedence_validated",
        )
        self.assertEqual(snapshot["dip"]["deterministic_policy_engine_readiness_percent"], 80.0)
        self.assertEqual(snapshot["dip"]["computed_simulation_diff_readiness_percent"], 80.0)
        self.assertEqual(snapshot["dip"]["durable_case_store_readiness_percent"], 95.0)
        self.assertEqual(snapshot["dip"]["identity_backed_approval_readiness_percent"], 85.0)
        self.assertEqual(snapshot["dip"]["release_management_readiness_percent"], 95.0)
        self.assertEqual(snapshot["dip"]["runtime_execution_readiness_percent"], 0.0)
        self.assertEqual(snapshot["dip"]["production_decision_authority_percent"], 0.0)
        self.assertEqual(snapshot["dip"]["implementation_backlog_defined_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["implementation_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["target_repo_evidence_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["target_repo_governance_clean_percent"], 100.0)
        self.assertEqual(snapshot["dip"]["approver_subject"], "Raghurammutya@gmail.com")
        self.assertEqual(snapshot["dip"]["target_repo_state"], "local_pre_runtime_trust_loop_observed")
        self.assertEqual(snapshot["dip"]["first_wedge"], "Governed Decision Review and Simulation")

    def test_write_snapshot_materializes_json(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "api.json"

            snapshot = write_snapshot(Path("."), out, "2026-05-23T00:00:00+00:00")

            written = json.loads(out.read_text(encoding="utf-8"))
            self.assertEqual(written["api_version"], "v1")
            self.assertEqual(written["generated_at"], snapshot["generated_at"])


if __name__ == "__main__":
    unittest.main()
